Requirements/Requirements/Controllers/RolesController.cs
namespace Requirements.Controllers
{
    using Requirements.Data.Entities;
    using Requirements.Helpers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    [Authorize(Roles = "Administrador")]
    public class RolesController : Controller
    {
        private readonly IRoleManager roleManager;

        public RolesController(IRoleManager roleManager)
        {
            this.roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await roleManager.GetAllRolesAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var role = await roleManager.FindByIdAsync(id);
            
            if (role == null)
            {
                return NotFound();
            }

            var model = new Role
            {
                Name = role.Name
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Role model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByNameAsync(model.Name);
                if (role == null)
                {
                    role = new Role
                    {
                        Id = model.Id,
                        Name = model.Name,
                    };

                    var result = await roleManager.CreateAsync(role);
                    if (result != IdentityResult.Success)
                    {
                        ModelState.AddModelError(string.Empty, "The role couldn't be created.");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError(string.Empty, "The role is already registered.");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await roleManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await roleManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            await roleManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Role model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id);

                if (role != null)
                {
                    role.Name = model.Name;


                    var result = await roleManager.UpdateAsync(role);
                    if (result != IdentityResult.Success)
                    {
                        ModelState.AddModelError(string.Empty, "The role couldn't be updated.");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Role no found.");
                }

            }
            return View(model);
        }
    }
}

Requirements/Requirements/Controllers/StatusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Requirements.Data;
using Requirements.Data.Entities;
using System.Linq;
using System.Threading.Tasks;

namespace Requirements.Controllers
{
    public class StatusController : Controller
    {
        private readonly DataContext context;

        public StatusController(DataContext context)
        {
            this.context = context;
        }

        // GET: Status
        public async Task<IActionResult> Index()
        {
            return View(await context.Statuses.ToListAsync());
        }

        // GET: Status/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Status/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Status model)
        {
            if (ModelState.IsValid)
            {
                var status = await context.Statuses.FindAsync(model.Name);
                if (status == null)
                {
                    context.Add(model);
                    await context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError(string.Empty, "Ya ha sido registrado un estado con este nombre");
            }
            return View(model);
        }

        // GET: Status/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await context.Statuses.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(status);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var status = await context.Statuses.FindAsync(id);
            context.Statuses.Remove(status);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(string id)
        {
            return context.Statuses.Any(e => e.Id == id);
        }
    }
}

Requirements/Requirements/Controllers/UsersController.cs
namespace Requirements.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Requirements.Helpers;
    using Requirements.Models;
    using System.Threading.Tasks;

    [Authorize(Roles = "Administrador")]
    public class UsersController : Controller
    {
        private readonly IUserManager userManager;
        private readonly IRoleManager roleManager;

        public UsersController(IUserManager userManager, IRoleManager roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await userManager.GetAllUsers());
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            await userManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var vm = new RegisterNewUserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RegisterNewUserViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(vm.Id);
                if (user != null)
                {
                    user.FirstName = vm.FirstName;
                    user.LastName = vm.LastName;

                    var result = await userManager.UpdateAsync(user);
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError(string.Empty, "La información de la cuenta no pudo modificarse correctamente");
                        return View(vm);
                    }

                    ViewBag.Message = "La información de la cuenta ha sido actualizada";
                    return View(vm);
                }
            }

            return View(vm);
        }
    }
}

Requirements/Requirements/Views/Shared/_AccountMenuPartial.cshtml
@if (User.IsInRole("Administrador") && User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a asp-area="" asp-controller="Status" asp-action="Index" class="nav-link">Estados</a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Projects" asp-action="Index" class="nav-link">Proyectos</a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Requirements" asp-action="Index" class="nav-link">Requisitos</a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Users" asp-action="Index" class="nav-link">Usuarios</a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Roles" asp-action="Index" class="nav-link">Roles</a>
    </li>
}
else if (User.IsInRole("Analista") && User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a asp-area="" asp-controller="Projects" asp-action="Index" class="nav-link">Proyectos</a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Requirements" asp-action="Index" class="nav-link">Requisitos</a>
    </li>
}
else if (User.IsInRole("Cliente") && User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a asp-area="" asp-controller="Requirements" asp-action="Index" class="nav-link">Requisitos</a>
    </li>
}

Requirements/Requirements/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Plan-A</title>

    <environment include="Development">

        <link rel="icon" href="https://getbootstrap.com/docs/4.1/assets/img/favicons/favicon.ico">

        <link rel="shortcut icon" href="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/favicon.ico" />

        <title>Cover Template for Bootstrap</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/cover/">

        <!-- Bootstrap core CSS -->
        <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="https://getbootstrap.com/docs/4.1/examples/cover/cover.css" rel="stylesheet">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Plan - A</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    @await Html.PartialAsync("_AccountMenuPartial")
                </div>
                <div class="navbar-nav ml-auto">
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content mt-4">
        @RenderBody()
        <hr />
        <!-- Footer -->
        <footer class="page-footer font-small special-color-dark pt-4">

            <!-- Footer Elements -->
            <div class="container">

                <!-- Social buttons -->
                <ul class="list-unstyled list-inline text-center">
                    <li class="list-inline-item">
                        <a class="btn-floating btn-fb mx-1">
                            <i class="fab fa-facebook-f"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-tw mx-1">
                            <i class="fab fa-twitter"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-gplus mx-1">
                            <i class="fab fa-google-plus-g"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-li mx-1">
                            <i class="fab fa-linkedin-in"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-dribbble mx-1">
                            <i class="fab fa-dribbble"> </i>
                        </a>
                    </li>
                </ul>
                <!-- Social buttons -->

            </div>
            <!-- Footer Elements -->
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2019 Copyright:
                <a href=""> Plan - A. Development Company.</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM">
        </script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>